# This is configuration for development environment
---
region: eu-west-1
cidr: 10.1.0.0/16
subnet_size_bits: 4
private_subnets: 
  eu-west-1a: 1
  eu-west-1b: 1
  eu-west-1c: 1
public_subnets:
  eu-west-1a: 1
  eu-west-1b: 1
  eu-west-1c: 1
